service: meraki-webhook-listener

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    MERAKI_WEBHOOK_SECRET: REPLACE-WITH-YOUR-SECRET-HERE

functions:
  merakiWebhookListener:
    handler: handler.merakiWebhookListener
    events:
      - http:
          path: webhook
          method: post
          cors: true
